### ISSUE TITLE
Locally-Regularized DTW presentation

### ISSUE THREAD

**Issue by bendichter** [rtavenar/tslearn#1]
Locally-Regularized DTW sounds really interesting. I'm familiar with regularization in regression problems, but I am not sure how it fits into this context. I am looking forward to your presentation on this topic!

Ben

**Comment by rtavenar** [comment]
Let me know if the doc added on this topic helps: 
http://tslearn.readthedocs.io/en/latest/metrics.html#locally-regularized-dynamic-time-warping

Best,
Romain

**Comment by bendichter** [comment]
Yeah that makes sense.  I think it would help if those examples were copied into the documentation. I noticed that `tslearn.metrics.dtw_path` outputs a path and a score, whereas `tslearn.metrics.lr_dtw_path` only outputs a score. I understand that this is because lr_dtw really outputs something like a probability distribution, and simplifying this to a path would be throwing out information. Surely there are some applications where the entire distribution is appropriate and some where the maximum likelihood solution is all that is needed. Is there any way of outputting the path that minimizes the given cost function?

I am curious how you implement lr_dtw. It seems like it could be solved as a special case of an HMM, where the state transition matrix is fixed as something like this:
```
A = 
q_h q_d q_i 0   0   0 ...
0   q_h q_d q_i 0   0 ...
0   0   q_h q_d q_i 0 ...
...

init_state = 1 0 0 0...
```
where q_h, d, and i are priors for horizontal, diagonal, and vertical transitions. (I may have gotten the orientation of that matrix wrong.) This would give you a probability distribution over states. q_h  = q_d = q_i would be a probabilistic version of dtw, but you could change it to prefer diagonal movement with q_d > q_h, q_d > q_i.

Ben

**Comment by rtavenar** [comment]
About `tslearn.metrics.lr_dtw_path`, I fixed the doc, thanks for pointing out the error in it (it actually outputs the path).

I tried to improve the doc for LR-DTW so that it is clearer that local transition probabilities are not fixed beforehand but rather learned during the alignment. I guess an arxiv paper would be a good way to provide more in-depth description of the method. I should do it as soon as I find time for it.

Finally, I will try to include notebooks to the docs (seems nbsphinx is the correct tool for that) asap.

**Comment by bendichter** [comment]
I was really hoping for a single path from `lr_dtw_path` in the same form as `dtw_path`-- a list of integer pairs. Could one simply run the "best path finder" (the second half of dtw-- the part after you compute the cost matrix, `cydtw.pyx` lines 41-69) on (1 - the probability map that is currently the output of `lr_dtw_path`)?

**Comment by bendichter** [comment]
And in the HMM implementation of DTW described above, the states would be probabilistic. `h`, and `i` are analogous to gamma, creating a prior which dictates how probable a diagonal move is vs. a skip.

**Comment by rtavenar** [comment]
The doc now includes example notebooks.

Concerning LR-DTW, the principle is that it considers several paths instead of a single one in order to improve on DTW's sensitivity to noise, so what you suggest would not make much sense I'm afraid.

For the link with HMM, the main difference is that with LR-DTW we do not favor such or such transitions, instead we learn transition probabilities in a data-dependent fashion.

**Comment by rtavenar** [comment]
I close this issue since the related code has been moved to tslearn_addons repo.
