### ISSUE TITLE
Loading large dataset

### ISSUE THREAD

**Issue by mmar30** [rtavenar/tslearn#106]
Hello,
I have a question about loading a dataset. I have a very large dataset. A class has the dimensions 946, 2000 where a time series has a length of 2000 and the dataset has 946 trials. I also want to combine several classes with the same dimensions into one dataset. Is the to_time_series_dataset suitable for this or is there another possibility?

**Comment by rtavenar** [comment]
Hi @mmar30 

Sorry for the delay in the answer. Basically, `to_time_series_dataset` is the only way to cast your data to an array with the correct shape. However, if the data cannot fit in memory, it is likely that you will have to work per-batch or select another toolbox, since `tslearn` relies on data stored in memory.

Best regards,
Romain
