### ISSUE TITLE
Evalute clustering results but doesn't get ideal scores

### ISSUE THREAD

**Issue by pahome** [rtavenar/tslearn#112]
What I met a problem is I do time-series clustering, and I found the clustering evaluation isn't ideal.

```
>>> a # It's a time-series array with 10 time intervals.
array([[  0,   0, 100,   0,   0,   0,   0,   0,   0,   0],
       [100,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 100,   0]])

>>> labels_ideal
[1, 1, 0]
>>> labels_wrong
[1, 0, 1]

```

In this array, arr[0] and arr[1] should be the same group. Then I want to check it by evaluating is with `tslearn.silhouette_score`:
```
>>> import tslearn.clustering as tsclu
>>> tsclu.silhouette_score(a, labels_ideal)
-0.3333333333333333  <--(1)
>>> tsclu.silhouette_score(a, labels_wrong)
0.6666666666666666   <--(2)
```
score (1) < (2)

What I thought is labels_ideal is what ideal, but its score is lower than (2)

Do I misunderstand something?

**Comment by johannfaouzi** [comment]
The results are good because the default metric is Dynamic Time Warping (DTW). The DTW score between the first and third time series is 0, while the DTW score between the second and the first (and third) time series is positive. It may sound counter-intuitive, but having a different value for the first or last index will lead to a positive cost in DTW.

I think that you should find a metric that is more suited for your definition of 'close' and 'far' time series. Maybe DTW with a global constraint (see the [documentation of dtw](https://tslearn.readthedocs.io/en/latest/gen_modules/metrics/tslearn.metrics.dtw.html)) or something else (that would be based on the indices if I had to guess).

I hope that this helps you a bit!
