### ISSUE TITLE
AttributeError: 'KNeighborsTimeSeries' object has no attribute 'd'

### ISSUE THREAD

**Issue by thusithathilina** [rtavenar/tslearn#122]
When using KNeighborsTimeSeries I'm getting below error. tslearn version is 0.1.28.2

```
dist, ind = knn.kneighbors(test_windows.values, return_distance=True)
  File "C:\Python36\lib\site-packages\tslearn\neighbors.py", line 166, in kneighbors
    return_distance=return_distance)
  File "C:\Python36\lib\site-packages\tslearn\neighbors.py", line 68, in kneighbors
    X = X.reshape((X.shape[0], -1, self.d))
AttributeError: 'KNeighborsTimeSeries' object has no attribute 'd'
```

**Comment by rtavenar** [comment]
Hi @thusithathilina 

In fact, you should not interact with `KNeighborsTimeSeries` that is meant to be an abstract class.
For classification purposes, you should rather use `KNeighborsTimeSeriesClassifier` (see doc [there](https://tslearn.readthedocs.io/en/latest/gen_modules/neighbors/tslearn.neighbors.KNeighborsTimeSeriesClassifier.html#tslearn.neighbors.KNeighborsTimeSeriesClassifier)).

The best fix to apply, I guess, would be to remove those abstract classes from the public documentation so that the confusion does not occur too often. Thanks for pointing that, I will do so for the next `tslearn` version!

Best regards,
Romain

**Comment by rtavenar** [comment]
On `dev` branch, the following code:

```python
from tslearn.neighbors import KNeighborsTimeSeries
import numpy as np

n_samples, n_features, n_timestamps = 20, 3, 50
rng = np.random.RandomState(42)
database = rng.randn(n_samples, n_features, n_timestamps)
queries = rng.randn(3, n_features, n_timestamps)

knn = KNeighborsTimeSeries()
knn.fit(database)
dist, ind = knn.kneighbors(queries, return_distance=True)
```

works.

So I suggest we close the PR and just add an example in the gallery of examples for this kind of nearest neighbor searches without classsification purposes.

Would that be OK for you @thusithathilina ?

**Comment by rtavenar** [comment]
Woops, I referenced a bad Issue number in my commit. The new example in the doc is in dev: https://github.com/rtavenar/tslearn/commit/0fc9dcd4f71693a4a98acea781cf350e4436653f and will be in the online docs as soon as we release 0.2.
