### ISSUE TITLE
Multidimensional KShape

### ISSUE THREAD

**Issue by TomohitoNakano** [rtavenar/tslearn#131]
Hello,

When we use the KShape algorithm in tslearn, can I apply the algorithm to multi-dimensional data?
The code can receive the multi-dimensional data, for example X.shape=(10, 300, 8) not like (10, 300, 1), but I can't understand what occurs in this code.

In this case, how do this code calculate the _inertia? Is there some weights for each dimension?

I read the original paper, but I couldn't get how to extend this algorithm to multi-dimensional data. 

When one dimensional data, my calculated SBD is equal to the output( _inertia ), but when >=2d, the output doesn't match my result.

So please help me.

**Comment by rtavenar** [comment]
Dear @TomohitoNakano 

Thanks for your interest in tslearn. Distances are computed [there](https://github.com/rtavenar/tslearn/blob/master/tslearn/clustering.py#L768-L770) based on the Cython function defined [there](https://github.com/rtavenar/tslearn/blob/master/tslearn/cycc.pyx#L46).

To be honest, it has been a while since I last dig in that code, so I prefer not to answer your question right now since I would be likely to write false claims. I could have a look at that later once we have released version 0.2 (which is the hot topic for tslearn at the moment).

If the code helps you find out why your results differ in dimension greater than 1, do not hesitate to post your hint here.

Romain

**Comment by TomohitoNakano** [comment]
Dear @rtavenar 

Thanks a lot for your prompt reply !
I think I specify the target code here for my problem.

`return numpy.real(cc).sum(axis=-1) / denom`

So summing up along the dimensional axis, right (weights = all 1)?

Thank you !

**Comment by rtavenar** [comment]
Yep, that is what this line does.
