### ISSUE TITLE
Very low code coverage for sklearn_patches.py

### ISSUE THREAD

**Issue by johannfaouzi** [rtavenar/tslearn#134]
Codeclimate shows that [sklearn_patches.py](https://codeclimate.com/github/rtavenar/tslearn/tslearn/tests/sklearn_patches.py/source) has only 13% code coverage. Since it is in the `tests` folder, it should have 100% code coverage. 

A lot of code is currently never used (all the functions, the current code coverage comes mostly from the imports). You can check the `coverage`box to see which lines are never run (red lines).

**Comment by johannfaouzi** [comment]
If you want a function to be run during the test routine, it must start with `test_`.

**Comment by rtavenar** [comment]
Hi @johannfaouzi 

I agree that this might be the issue (I don't know how code coverage is performed under the hood, I have to admit). 

If you can adapt the imports (just list everything from sklearn_patches.py I guess) and see locally if it changes anything in terms of code coverage, that would be great. Otherwise I can do it tomorrow (I'm off today).

**Comment by GillesVandewiele** [comment]
Hi guys,

Sorry about this.. I'm indeed on holidays until 10/09, but I can take a look after that :)
