### ISSUE TITLE
[HELP!!!] Any way to set 'sakoe_chiba_radius' in metric_param for tslearn.clustering.TimeSeriesKMeans

### ISSUE THREAD

**Issue by chinghoo** [rtavenar/tslearn#146]
any way to set 'sakoe_chiba_radius' in metric_param for tslearn.clustering.TimeSeriesKMeans when metric is 'dtw'?
the following does not work!!! this makes me crazy for all night today!!!Help!!!

TimeSeriesKMeans(n_clusters=3, metric="dtw", max_iter=5,
...                            max_iter_barycenter=5,
...                            metric_params={"sakoe_chiba_radius": .5},
...                            random_state=0)

**Comment by GillesVandewiele** [comment]
After closely inspecting the code, I may have found what is going on.

cdist_dtw is called within TimeSeriesKMeans. The definition is:
```
def cdist_dtw(dataset1, dataset2=None, global_constraint=None,
              sakoe_chiba_radius=1, itakura_max_slope=2., n_jobs=None):
```

Now when looking at the comments at `sakoe_chiba_radius`, I see: 
```
Radius to be used for Sakoe-Chiba band global constraint. Used only if
        ``global_constraint="sakoe_chiba"``.
```

So `global_constraint: "sakoe_chiba"` must also be passed with metric_params!

@rtavenar this is pretty unclear from the docs I'd say and I had to look into the code to figure this out. It would be more user-friendly that this global_constraint is inferred whenever needed (e.g. when either `sakoe_chiba_radius` or `itakura_max_slope` is passed in the `metric_params` dictionary.

**Comment by rtavenar** [comment]
Hi @chinghoo 

Thanks @GillesVandewiele for your prompt reply. Indeed, it is expected that global_constraint is set to "sakoe_chiba" for sakoe_chiba_radius to be used.

The thing is, as it is implemented now, distances to centroids are computed using this constrained DTW, but DBA algorithm does not have a sakoe_chiba_radius or itakura_max_slope parameter, so this is not satisfactory.

And this is also true for other estimators that use DTW, but for kNN for example, the only problem is the one raised by @chinghoo since only cdist_dtw is used there.

Finally, I am not sure how to fix things, since sakoe_chiba_radius has a default value that cannot be easily differentiated from an user-input value (no None by default). 
Maybe the fix would be to set the default for these parameters as None, but document the fact that this default corresponds to specific values (the current default ones) such that we do not introduce any backward incompatibility.

If you can work on that PR, that would be cool (branch from dev if you do so).

**Comment by rtavenar** [comment]
A quick fix on master could be tu just add an example with constrained DTW to the docs for kNN estimators (not fork means since the implementation is not satisfactory, so we should not advertise for that at the moment).

And the constrained DBA should be available asap, ideally in v0.3, I can take care of that, I guess.

**Comment by GillesVandewiele** [comment]
One other way would be, wherever metric_params is used, to automatically add the `global_constraint` key whenever `sakoe_chiba_radius` or `itakura_max_slope`. It's not ideal, since it would require similar code on different places, so I will think about a better solution for this and I will get back to you!

**Comment by chinghoo** [comment]
@GillesVandewiele 
Thank you so much for your reply, my problem solved. Inspecting the source code is important!!

**Comment by rtavenar** [comment]
I just created a related PR. @GillesVandewiele, could you give your opinion on the choices made there?

**Comment by GillesVandewiele** [comment]
Great @rtavenar I will do this right now!

**Comment by rtavenar** [comment]
Thanks @GillesVandewiele 

This now in dev branch on github, and will be integrated (automatic constraint setting + TimeSeriesKMeans with constrained DBA) in tslearn v0.3.
