### ISSUE TITLE
[Question] Pytest framework?

### ISSUE THREAD

**Issue by cr458** [rtavenar/tslearn#17]
Hi @rtavenar , just wondering if there is any interest in moving towards a `pytest` based testing framework for tslearn, perhaps something that mirrors sklearn?
If so, this is something I have some experience in and would be more than happy to begin helping out with!

**Comment by rtavenar** [comment]
Hi!

I have very little experience in tests, so that would be great if you could help on this. At the moment, I only use doctests, but it would definitely make sense to mix them with proper tests when needed, just to make the doc simpler.

The thing is I know there are failing tests at the moment. Maybe it would be better if I tried to fix them first, then you fork the project and setup a pytest testing environment and do a pull request? What do you think?

**Comment by cr458** [comment]
Sounds good! If the failing tests are quick fixes then that sounds like a good. Otherwise I can always start with a simple test just to show the expected usage of `pytest` to get the ball rolling. Let me know whatever you prefer, you've done something incredible here and am happy to help out however!

**Comment by rtavenar** [comment]
Hi,

Now, it seems OK, the issue was related to `numpy` in version `>1.14` changing the way it formats strings representing arrays. For the moment, the fix is I force to use `numpy=1.3`, but I guess this could be fixed by moving all the tests that fail to non-doctests (hence, the comparison would not be based on strings anymore).

Anyway, thanks a lot for participating in `tslearn`, and let me know if you have issues on which I could help.

**Comment by cr458** [comment]
No problem. Really happy to be able to contribute to your hard work! Will have a look at first converting the failing tests, could you tell me where they were?

**Comment by rtavenar** [comment]
Here is an example of a failing test:
```File "/home/travis/build/rtavenar/tslearn/tslearn/barycenters.py", line 43, in tslearn.barycenters.EuclideanBarycenter
Failed example:
    bar  # doctest: +ELLIPSIS
Expected:
    array([[ 1. ],
           [ 2. ],
           [ 3.5],
           [ 4.5]])
Got:
    array([[1. ],
           [2. ],
           [3.5],
           [4.5]])
```

And the same happened for all tests for which the output is a `numpy` array.

**Comment by rtavenar** [comment]
Maybe at some point, it would be good to test estimators in the `Pipeline` framework of `sklearn` (cf Issue #19 ).

**Comment by rtavenar** [comment]
I close this issue since pytest is now used for testing (current dev branch, forthcoming 0.2 version)
