### ISSUE TITLE
A way to unscale data

### ISSUE THREAD

**Issue by jaumebp** [rtavenar/tslearn#186]
Hi,

I'm using the TimeSeriesKMeans on some data I got, and it gives much better results after scaling it with TimeSeriesScalerMeanVariance. However, I'd like to plot the centroids in the original data representation. Is there an easy way to unscale them?

Thanks, this is a very nice library!

**Comment by rtavenar** [comment]
Hi @jaumebp 

This method scales the time series independently.
Hence, there is not a single mean / variance vector for the whole dataset that could be used to "unscale" the centroids, I'm afraid.
And if the goal is visualization, I would suggest not trying to unscale anything when the clustering has been based on scaled data, since the resulting visualization could be misleading.

Hope this helps,
Romain
