### ISSUE TITLE
Updating the contributing guide on master for the next patch release

### ISSUE THREAD

**Issue by johannfaouzi** [rtavenar/tslearn#203]
PR #197 was merged on the `dev` branch. Do you want me to open another PR to target the `master` branch? Or maybe someone who is good enough at git could explain how to merge only specific commits to another branch?

**Comment by rtavenar** [comment]
Is your branch still somewhere on your repo? Wouldn't a rebase do the trick?

**Comment by rtavenar** [comment]
I am no git master, so I might be completely wrong, but I would try to:

0. sync your master with mine
1. create a new branch `newbranch` from master
2. rebase your PR branch to `newbranch`
3. create a new PR from this new branch to be merged to master

WDYT?

**Comment by johannfaouzi** [comment]
I have the branch on my local version, but I was referring to the main repo. We merged this PR on dev, but we would like to have the changes for the next patch release (0.3.1), so we need to port the changes to `master`.

Two possibilities:
* I open another PR (with my branch) targeting `master`, or if you are a git master,
* You could probably merge this commit to master yourself.

For `scikit-learn`, you always target `master` when making a PR, but to release a patch version, I think they select a subset of all the merged PRs (those with bug fixes) and merge them all (I think). Tagging the expert @rth (I always wondered how to do this).

**Comment by rth** [comment]
> For scikit-learn, you always target master when making a PR, but to release a patch version, I think they select a subset of all the merged PRs (those with bug fixes) and merge them all (I think).

well yes, in scikit-learn  (or numpy, pandas etc) PRs are squashed now, so each corresponds to 1 commit in the dev branch (there master) and then each one can be easily added to a branch used to create backports for some version either with `git cherry-pick` or  interactive rebase https://scikit-learn.org/stable/developers/maintainer.html#preparing-a-bug-fix-release

In this case, since merge commits are used, I'm not fully sure how to proceed, haven't used non squashed merges in a while. But yeah, as @rtavenar mentioned creating a branch from master, then either rebasing (or merging, though likely not recommended without squashing) things into it to make the diff look right and opening a PR sounds reasonable.
