### ISSUE TITLE
plot_kmeans example: unscale cluster centers

### ISSUE THREAD

**Issue by ssimontacchi** [rtavenar/tslearn#206]
Such a cool library! 

Just wondering: in the plot_kmeans example you scale the data before running k-Means. I want to visualize the km._cluster_centers_ scaled back to their original values. 

What do you think would be the best way to do that? I have been tinkering around but haven't figured it out yet. Thanks so much for the advice!

**Comment by rtavenar** [comment]
Hi @ssimontacchi ,

Glad you like `tslearn`!

This should probably be discussed in the docs, maybe we could improve it in the context of #204 .

In short, the answer is: one cannot scale barycenters back to data range because each time series is scaled **independently** (scaling is such that each time series has 0 mean and unit variance in this case). The assumption here is that the range of a given time series is uninformative and one only wants to compare shapes in a scale invariant manner (when time series are multivariate, this also rescales all modalities such that there will not be a single modality responsible for a large part of the variance).

**Comment by rtavenar** [comment]
@ssimontacchi 

Could you please provide feedback on the new text for this example: https://github.com/rtavenar/tslearn/pull/204/commits/9d86ccfcc6e6e0ea627d04656c524c3df7665709#diff-c56bcf5a2beebaf227047f7eb181269c

If it answers your question, it will be included in the soon-to-be-released tslearn v0.3.1

**Comment by ssimontacchi** [comment]
Really helpful!
