### ISSUE TITLE
Predict method throwing an error with KNeighborTimeSeriesClassifier

### ISSUE THREAD

**Issue by wahidelchaar** [rtavenar/tslearn#217]
**Describe the bug**
I am trying to create a KNeighborsTimeSeriesClassifier (with 'dtw') on some labelled panel data. The data has total 15,123 time series where the largest one has 20,546 rows (The time series have different lengths), and they all have 10 features. So the shape of the tslearn-formatted data is (15123, 20546, 10). Fitting the classifier ran without any errors, but the problem is when I call the predict method: If I pass all the test data for prediction, the code runs indefinitely and never finishes (Keep in mind that I am using a powerful EC2 instance, so computing power and memory should not be an issue). If I try to pass in just one time series of the test data, I get the following error:

`ValueError: Input contains NaN, infinity or a value too large for dtype('float64').`

**To Reproduce**
Unfortunately, I cannot share what the data looks like because it is the intellectual property of my employer, but I can share the code:
```python
# Format data to meet tslearn format requirements:
X3d = np.array(list(X.groupby('ID').apply(pd.DataFrame.as_matrix)))

list_of_X = []
for arr in range(0,X3d.shape[0]):
    array = np.delete(X3d[arr],0,axis=1)
    list_of_X.append(array)

list_of_X = [arr.tolist() for arr in list_of_X]

X = to_time_series_dataset(list_of_X)

# Shuffle and split the data into train and test
indices_shuffle = np.random.permutation(X.shape[0])
X_shuffle = X[indices_shuffle]
y_shuffle = y_values[indices_shuffle]

import math
X_train = X_shuffle[:math.floor(X_shuffle.shape[0]/1.25)]
X_test = X_shuffle[math.floor(X_shuffle.shape[0]/1.25):]
y_train = y_shuffle[:math.floor(X_shuffle.shape[0]/1.25)]
y_test = y_shuffle[math.floor(X_shuffle.shape[0]/1.25):]

# Transform the data
from tslearn.preprocessing import TimeSeriesScalerMeanVariance

scaler = TimeSeriesScalerMeanVariance(mu=0,std=1.)
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

# Fit the classifier
from tslearn.neighbors import KNeighborsTimeSeriesClassifier

clf = KNeighborsTimeSeriesClassifier(metric='dtw',n_neighbors=1,n_jobs=-1)
clf.fit(X_train, y_train)

# Score the data
print('Accuracy: {}'.format(clf.score(X_test[0],y_test[0]))
# This is where I get the error!
```

**Expected behavior**
I expect the code to return an accuracy score.

**Environment (please complete the following information):**
 - OS: ubuntu:16.04
 - tslearn==0.30.1
 - I am running this inside an isolated Docker container on Amazon SageMaker

**Additional context**
For the last line of code, I also tried calling `clf.predict(X_test[0])` but it returned the same error. I suspect that the issue may be with the transformer, but I am not sure.

**Comment by rtavenar** [comment]
Hi @wahidelchaar and thanks for reporting this.

I understand that you cannot share the data that lead to this behavior, but could you at least try to reproduce the behavior with synthetic data?

There are several questions in your post, but I can try to answer some of them:
* this is not very surprising that DTW computations (and you have lots of them) are computationally expensive:
  1. DTW runs in O(T^2) time where T is the length of the time series at stake, and your time series are especially long
  2. at the moment, DTW computations are parallelized in terms of rows (ie. calls to DTW for different test instances can be run in parallel) but not columns (ie. calls for different train instances) -> **maybe this point could be worth investigating in order to speed up computations when you have large training set and small test set**
* in your code above, if you run `clf.predict(X_test[0])`, then `tslearn` will try to map `X_test[0]` to a time series **dataset** format of shape (20546, 10, 1) instead of (1, 20546, 10), which is supposed to fail since the test data does not have the same dimension as the input data. This makes me thinks that:
  1. checking test dimensionality and having dedicated fail message would be helpful, this is Work In Progress, cf #174 )
  2. what would you get if you ran `clf.predict(X_test[:1])` (that would have the correct (1, 20546, 10) shape) instead?

**Comment by wahidelchaar** [comment]
@rtavenar Thank you for your quick reply! I wanted to create synthetic data for you to reproduce, but first I decided to try out your method of using `clf.predict(X_test[:1])`. It worked! The only problem is that it took 1.5 hours to run this one time series prediction... and this would not be feasible for 15123 time series. Is there anything we can do? I would love to be able to use tslearn in this project.

**Comment by rtavenar** [comment]
OK, so the good news is that its not a bug. Then, for your more general question, DTW is clearly a costly method when long time series are at stake. Would it make sense for you to subsample your series ?

**Comment by wahidelchaar** [comment]
@rtavenar I don't believe that I can sacrifice data by subsampling, as my research has proven that this is the minimum amount of data that can help an ML algorithm discern between class 0 and 1. I could break up each ID into smaller time series, but that would violate the assumption of IID rows. I have tried tsfresh, which has so far given me 70% recall and 80% AUC - but I wanted to try other methods such as tslearn. Any recommendations?

**Comment by rtavenar** [comment]
Why not trying ShapeletModel, which is likely to scale well, as soon as you do not set shapelet length to a too high value.

**Comment by wahidelchaar** [comment]
@rtavenar it can handle time series with variable lengths?

**Comment by rtavenar** [comment]
Ah, no, at least not as it is implemented now, sorry I forgot that point.

**Comment by wahidelchaar** [comment]
Thanks for your help! In the future I will be researching the effectiveness of grabbing X points of data for each ID, instead of what I am doing right now (grabbing Y days of data for each ID). At that point it will make sense to try your models that do not work with varying time series lengths. I will now close this issue.
