### ISSUE TITLE
Extract K top-shapelets with lengths in interval

### ISSUE THREAD

**Issue by GillesVandewiele** [rtavenar/tslearn#35]
Hello,

First of all, really great work on this repository, very helpful! 

I would like to extract the "best" `K` from a set of timeseries. The length of these shapelets should be within the interval '[min_len, max_len]'. I was wondering how I best approached this, since the `n_shapelets_per_size` hyper-parameter has an impact on the output. 

I currently see two alternatives:
1) Create a dictionary with keys all values between `min_len` and `max_len` and each value equal to `K`. In the end, iterate over all extracted shapelets and select the best `K` based on a metric such as information gain.
2) A for-loop iterating over each value in the interval, creating a simple dictionary {l: K} and apply the shapelet learning. Append all the extracted shapelets in each iteration to a list and in the end, select the best `K` from that list.

Is there any alternative better than the other? Or is there a third option that I currently cannot think of?

Thanks in advance,

Gilles

**Comment by rtavenar** [comment]
Hi,

I'm not sure what the best way to do so would be, but definitely, the implementation found in `tslearn`, which is based on Learning Time Series Shapelets by Grabocka et al. is not the best, since it aims at finding optimal shapelets for a fixed number of them and of fixed size. Using this implementation, only a grid search on the possible numbers and lengths could be performed I guess.
