### ISSUE TITLE
Retrieving cluster centers

### ISSUE THREAD

**Issue by Vayel** [rtavenar/tslearn#39]
When we cluster series (for instance with `KShape`), we obtain centers for normalized data. It would be convenient to have a method to retrieve centers as original time series.

**Comment by rtavenar** [comment]
Hi,

I have thought about it a bit, and it does not seem to me that there would be a way to do so that would make sense from a mathematical point of view, since centers are updated iteratively and have to be normalized at each iteration.

If you really need that, I would suggest you use another clustering method (cf the [`TimeSeriesKMeans`](http://tslearn.readthedocs.io/en/latest/gen_modules/clustering/tslearn.clustering.TimeSeriesKMeans.html#tslearn.clustering.TimeSeriesKMeans) class).

Best,
Romain
