### ISSUE TITLE
Failure to load UCR_UEA_datasets

### ISSUE THREAD

**Issue by JermellBeane** [rtavenar/tslearn#80]
```
data_train = numpy.loadtxt(os.path.join(full_path, fname_train), delimiter=None)
data_test = numpy.loadtxt(os.path.join(full_path, fname_test), delimiter=None)
```

should be changed to...

```
data_train = numpy.loadtxt(os.path.join(self._data_dir, fname_train), delimiter=None)
data_test = numpy.loadtxt(os.path.join(self._data_dir, fname_test), delimiter=None)
```

Never fear though, I will submit a pull request later. Documenting this for anyone who runs into this problem.

**Comment by JermellBeane** [comment]
This should really be titled... Failure to load UCR_UEA_datasets... Also can I suggest better error handling... I had no idea what was going on returning None, None, None, None upon error.

**Comment by JermellBeane** [comment]
Thanks for the cool library!!!!

**Comment by JermellBeane** [comment]
https://github.com/rtavenar/tslearn/blob/master/tslearn/datasets.py#L239

The offending line.

**Comment by MarcCoru** [comment]
Hi Jermell,

The format of zip files from the `http://www.timeseriesclassification.com/` website where the datasets are initially downloaded and then cached in `~/.tslearn/datasets/UCR_UEA` has changed recently.

One change was that contents of the zip are not unpacked in a new folder (named after the dataset), but the current one.
This is why in the latest version the `full_path` specifically defines the path to  `~/.tslearn/datasets/UCR_UEA/<dataset>` while the previous version just unpacked the zips in `~/.tslearn/datasets/UCR_UEA` and the <dataset> folders were unpacked from the zip.

I think it is likely that this issue is a conflict with cached files from the previous version.  Especially since Travis seems to succeed on the latest tslearn version, but not on the pull request.

Could you try deleting the cached datasets with `rm -r $HOME/.tslearn/datasets`. 
When executing your code, the datasets should be re-downloaded and unzipped then according to the latest version. 

```python
from tslearn.datasets import UCR_UEA_datasets
UCR_UEA_datasets().load_dataset("Yoga")
```

**Comment by JermellBeane** [comment]
I will try this later today. Thanks for responding.

**Comment by MarcCoru** [comment]
@JermellBeane any updates from your side? did it fix it?

**Comment by JermellBeane** [comment]
Seems to have fixed it, I must have had an older version. Sorry!
